import React from "react"
import Layout from "../components/Layout"

export default () => (
    <Layout>
        <h2>The Pacific War</h2>
        <p>
            Hello and welcome to the History page of my website. One of my passions in school has always been history. I want to share with you my knowledge of my favorite part of world history; the Pacific War. My goal with this website is to educate people on one of America's finest hours. Posting every Saturday, so stay tuned.
        </p>
        <h2>Background</h2>
        <p>
            <h3>Japanese Invasion of Manchuria: 1937</h3>
            <i> <b>The reason was the failure of both Japan and China to understand each other and the inability of America and the European powers to sympathize, without prejudice, with the peoples of East Asia.
            <br></br>-Hideki Tojo, Japanese Prime Minister</b></i>
            <br></br>
            <br></br>
            <i><b>Japan cannot conquer China with America in her rear, Soviet Russia on her right and England on her left - her most powerful enemies in the South Sea all flanking her. It is this international situation that constitutes one of Japan's great weaknesses.
            <br></br>-Chiang Kai Shek, Chinese Military Leader</b></i>
            <br></br>
            <br></br>
            The origins of the Pacific War can be traced all the way back to the end of World War I in 1918 during the Treaty of Versailles negotiations. Japan and the US had fought as the Allies with Britain, France, and Russia (pulled out in 1917) during World War I. They faced the Central Powers who were Germany, Austria-Hungary, Bulgaria, and the Ottoman Empire. As a result of the talks, Germany was forced to make reparation payments to all of the allied powers except for two nations: Russia and Japan. Japan, after being shunned by the Allies at the Versailles conference, were deeply angered. During the 1920s, Japan started to build up its army with fresh recruits, its navy with new, fast ships, and its air wing with new fighter and bomber variants. As Hitler came to power in Germany during the 1920s and 1930s, the power of the Japanese government had switched from the Emperor to military generals and admirals. They formed an oligarchy and kept the Emperor out from any military affairs. The armed forces in Japan had ultimate control and decided what the country was going to do during the Pacific War. These generals kept the Emperor Hirohito as a figurehead of the government. One of these generals who grabbed the reigns of power was Hideki Tōjō. Tōjō was born in the Kōjimachi district of Tokyo in 1884. Tōjō was born into a military family and joined the army in 1905. He joined the army in the closing days of the Russo-Japanese War in 1905. In 1934, Tōjō was promoted to the rank of major general. He was strongly opposed to the coup that was planned in 1936 on the Emperor. In 1937, Tōjō led the invasion on the Chinese province of Manchuria along with generals Shigeru Honjō, Jirō Tamon, and Senjuro Hayashi. The 7th Japanese division entering Manchuria was numbered at 60,450 men facing off against a 160,000 man Chinese resistance. The Japanese force under Tamon attacked southern Manchuria in 1931 with the Jinzhou operation and occupied the city of Jinzhou and Nanjing. The Chinese government, led by Chiang Kai Shek was forced to resign and the Japanese took most of southern Manchuria. A northern offensive in early 1932 by Tamon raided the city of Harbin and completed the invasion. The Chinese leader in the north, Ma Zhanshan was forced to join the new Japanese backed government in Manchuria. The invasion of Manchuria proved to be the first offensive grab by Japan into Asia and the Pacific. The blitzkrieg of Japanese troops took the Chinese completely by surprise and led to the outbreak of the Second Sino-Japanese war which began in 1937. 

            <h3>Second Sino-Japanese War: 1939-1945</h3>
            <i><b>Keep men, lose land: land can be taken again. Keep land, lose men: land and men are both lost.
            <br></br>-Mao Zedong, Chinese Communist Leader, Future Chinese President</b></i>
            <br></br>
            <br></br>
            <i><b>We shall not lightly talk about sacrifice until we are driven to the last extreme which makes sacrifice inevitable.
            <br></br>-Chiang Kai-Shek, Chinese Nationalist Leader</b></i>
            <br></br>
            <br></br>
            The Japanese invasion of Manchuria in 1937 became the precursor to the Second Sino-Japanese War which marked a six year conflict between China and Japan. For hundreds of years, China and Japan had been at each other's throats. This war with Japan and China had become more mechanized and deadly than previous wars. The Japanese took Manchuria and thus kept it until 1945 when the USSR invaded it. The war started initially with Japan taking over cities such as Harbin and Shanghai. Chiang Kai-Shek in response took a force and surrounded the Japanese International Settlement in Shanghai. The siege became a full scale battle and turned into the Battle of Shanghai. The Chinese launched airstrikes which hit the settlement. In response, the aircraft carrier force of the Japanese Navy launched many sorties into China. The fledgling Chinese Air Force was old and was comprised of World War I era biplanes. They were no match for the industrialized Japanese Air Force and Naval Air Arm which comprised of fast fighters and bombers. Examples were the Mitsubishi G4M "Betty" and the Nakajima Ki-27 "Nate". Many Chinese leaders knew that they would lose the war if the Japanese Navy and Air Force choked their supply lines from India and Burma. Chiang Kai-Shek made a deal with the General Claire Lee Chennault of the US Air Force. Chennault vowed to provide the Chinese with American pilots and planes to help address the Japanese atrocities. The American Volunteer Group or AVG was formed and became known throughout the world as the Flying Tigers. The Flying Tigers were the first time that Americans fought the Japanese in combat. The American and Chinese pilots accounted for 300 aerial victories in the new P-40 Warhawk. The skill of these pilots took the Japanese completely by surprise and caused them to halt bombings in mainland China. One of the major events of the Sino-Japanese War was the Nanking Massacre. After Japanese occupiers took control of the city of Nanking, they proceeded to rape and kill over 40,000-300,000 people. The Japanese showed their brutality to the world after the event became publicized. The world was shocked at what happened and remains one of the darkest periods in Chinese and world history. The war also marked the growing divide of the Communist party of China and the Nationalist party. Mao Zedong rose as one of the leading figures of the Communist party and Chiang Kai-Shek led the Nationalist party. After World War II, Mao Zedong and Chiang Kai-Shek would go to war over the idea of communism and would lead to a change in Chinese politics that continues into the modern era. The Second Sino-Japanese War marked the precursor to many events in Asia and the Pacific War as a whole.

            <h3>Japanese Moves In the Pacific: 1940-1942</h3>
            After the successful invasion of China, Japan was eager to extend its empire across the Pacific. Japan as an island nation, needed to expand and conquer many other nations to keep their war machine going. Their ships, planes, and army needed oil to continue to function. An invasion across the Pacific would also give them notoriety, and gain the attention of Germany and Italy. In 1940, the Japanese started their campaign. They invaded Vichy French Indochina which comprised of present day Vietnam, Cambodia, and Laos. The French had turned the colony into a natural resources base which supplied rubber and tea. A few days after the invasion, Japan withdrew from the League of Nations and signed a military alliance with Germany and Italy thus forming the Axis Powers. The Japanese then moved on to Malaya, Singapore, and the Dutch East Indies. These nations had big oil reserves, and provided the Japanese a base to anchor ships, and to conduct their offensives into India, Australia, and the South Pacific. As a response, the US, Australia, France, Britain, and the Netherlands imposed a natural resource embargo on Japan. After the embargo, the Japanese further expanded into the Caroline, Gilbert, Solomons, and Marianas islands. With their territorial gains, the Allied powers knew that war would be imminent with Japan. 
        </p>
        <h2>The Beginning</h2>
        <p>
            <h3>Pearl Harbor: December 7th, 1941</h3>
            <i><b>Yesterday, December 7, 1941—a date which will live in infamy—the United States of America was suddenly and deliberately attacked by naval and air forces of the Empire of Japan.
            <br></br>-Franklin Delano Roosevelt, President of the United States</b></i>
            <br></br>
            <br></br>
            <i><b>I fear all we have done is to awaken a sleeping giant and fill him with a terrible resolve.
            <br></br>-Isoroku Yamamoto, Supreme Japanese Naval Commander</b></i>
            <br></br>
            <br></br>
            On November 26th, 1941, a Japanese naval force left the home islands of Japan bound for Pearl Harbor in the Hawaiian islands. Their mission was to attack the US naval station and sink as many battleships and aircraft carriers as possible. The force was led by six aircraft carriers: Kaga, Akagi, Soryu, Hiryu, Shokaku, and Zuikaku. Accompanying them were the battleships Hiei and Kirishima, heavy cruisers Tone and Chikuma, light cruiser Abukuma, and 9 destroyers. The Japanese force reached the waters off Oahu on December 6th, 1941. In the morning hours of December 7th, the Japanese prepared and launched the first wave of dive and torpedo bombers. The aircraft force consisted of 89 Nakajima B5N "Kate" torpedo bombers, 51 Aichi D3A "Val" dive bombers, and 43 Mitsubishi A6M "Zero" fighters. They large force was detected by radar stations on Oahu, but was ignored because they were mistaken as Boeing B-17 bombers from California. The torpedo bombers reached Pearl at 7:48 am local time. The torpedo bombers sought the US Battleship force in the harbor while the dive bombers attacked nearby Hickam and Wheeler army air field. The battleship line was famously nicknamed "Battleship Row". The "Kate" torpedo bombers in the first wave sunk the battleships Arizona and Utah. The battleship Nevada tried to exit the harbor while under attack, but was sunk by two torpedoes. The first wave was replaced by a second wave which sunk battleships Oklahoma, West Virginia, California, Tennessee, Maryland, and Pennsylvania. The entire air arm of Hickam and Wheeler airfield were suppressed from launching a successful counterattack. The strike aircraft of the Japanese returned to their carriers at 1:00 pm local time. The main fleet units of the United States that were missing at Pearl Harbor were the aircraft carriers, Enterprise, Lexington, and Saratoga. The failure of the Japanese to sink the US carriers proved to be one of the major downfalls of the Japanese empire throughout World War II. On December 8th, 1941 President Franklin Delano Roosevelt managed to pass a declaration of war through Congress towards Japan. The US Congress also passed declarations of war on Germany and Italy. World War II had officially begun for the United States.
            
            <h3>First Indian Ocean Raid: March 31st, 1942 - April 10th, 1942</h3>
            <i><b>The most dangerous moment of the War, and the one which caused me the greatest alarm, was when the Japanese Fleet was heading for Ceylon and the naval base there. The capture of Ceylon, the consequent control of the Indian Ocean, and the possibility at the same time of a German conquest of Egypt would have closed the ring and the future would have been black.
            <br></br>-Winston Churchill, Prime Minister of the United Kingdom</b></i>
            <br></br>
            <br></br>
            After raiding the naval base at Pearl Harbor, the Japanese aircraft carrier force was sent to the eastern Pacific to raid British coastal bases at Ceylon (modern day Sri Lanka), Singapore, and Trincomalee island. The attack was designed to wipe out British fleet units that would attempt to attack the Japanese invasions of India, Burma, or Australia. The Japanese force under Admiral Chuichi Nagumo comprised of six aircraft carriers (Akagi, Soryu, Hiryu, Shokaku, Zuikaku, Ryujo), four battleships (Kongo, Hiei, Kirishima, Haruna), five cruisers (Tone, Chikuma, Abukuma, Suzuya, Kumano), and 19 destroyers left the Celebes islands for Ceylon. Meanwhile, the British Force A and Force B was under the command of Sir James Somerville. Force A had two aircraft carriers (HMS Formidable, HMS Indomitable), and 1 battleship (HMS Warspite). Force B had one aircraft carrier (HMS Hermes), four battleships (HMS Revenge, HMS Royal Sovereign, HMS Ramilles, HMS Resolution), and two cruisers (HMS Cornwall, HMS Dorsetshire). Somerville left the Maldives to intercept. On April 5th, 1942, the Japanese launched dive and torpedo bomber assaults on Colombo, Ceylon. The Japanese carriers sunk British destroyer HMS Tenedos, and cruiser HMS Hector. The cruisers Kumano and Suzuya sunk five merchant ships in the harbor. The Japanese aircraft also located Force B and sunk HMS Hermes. Nagumo's force chased HMS Cornwall, and HMS Dorsetshire  until they were sunk off the Maldives. After the raid on Colombo, the Japanese moved to Trincomalee where they sunk more British merchant shipping. The raid was a success for the Japanese who had sunk many tons of shipping by using their aircraft carriers. However, the British Eastern Fleet was saved thanks to Somerville's retreat. Thanks to the fear of Japanese carrier attacks, the British did not challenge the later raids on Darwin in Australia and the invasion of Guadalcanal. 
            
            <h3>The Doolittle Raid: April 18th, 1942</h3>
            <i><b>An attack on the Japanese homeland would cause confusion in the minds of the Japanese people and sow doubt about the reliability of their leaders.… Americans badly needed a morale boost.
            <br></br>-Lt. Col James Doolittle, US Air Force</b></i>
            <br></br>
            <br></br>
            <i><b>Those bombers must have came from 'our new base in Shangri-La'
            <br></br>-Franklin Roosevelt in response to a question on the Doolittle Raid</b></i>
            <br></br>
            <br></br>
            The Doolittle Raid was an aerial assault and strategic bombing run on the Japanese mainland and capital city of Tokyo. After the attacks on Pearl Harbor, the US war effort had barely gotten under way. Morale was at an all time low in the country. With the Axis forces wreaking havoc in Europe, the North Atlantic, and the Pacific, the US Navy devised the Doolittle Raid using two of the three new Yorktown class aircraft carriers. The carriers USS Enterprise and USS Hornet, cruisers Northampton, Vincennes, Nashville, and Salt Lake City, and eight destroyers were to shuttle Colonel Jimmy Doolittle and his land based bomber squadron of B-25 Mitchells to 200 miles off the coast of Japan. This would ensure enough fuel to take off, bomb Tokyo, and make it inland to mainland China. On April 17th, 1942, the Navy task force began radio silence. On the morning of April 18th however, the task force came across the Japanese picket boat Nitto Maru. After repeated gun salvos from USS Nashville, the Nitto Maru sank. Fears that the picket boat was able to radio the task force's position cause Admiral Mark Mitscher to give the order to launch the B-25s from USS Hornet at 750 miles from Japan. Doolittle readied his men for the mission. At 8:20 am local time, Doolittle launched his aircraft from the 467 foot strip of USS Hornet. The bombers had never taken off from the deck of an aircraft carrier. Consequently, many of the bombers nearly struck the water. However, the bombers made it off Hornet safely. The bombers hit many industrial factories in Tokyo, Osaka, Kobe, Yokosuka, and Nagoya. Doolittle headed west to the East China Sea where all but one of his bombers ditched. The bomber pilots were eventually rescued and Doolittle was awarded the Medal of Honor. The other B-25, piloted by Edward York landed and was interned in the Soviet Union. Overall, the raid was a success in that it increased morale in the US by giving Japan a "Pearl Harbor" of their own. It also showed that the US could stealthily strike Japan thanks to its carrier force. On the other hand, the bomb hits only caused superficial damage to the factories which still kept them in Japan's war effort. It wasn't quite like Pearl Harbor where the capabilities of the US Navy were severely reduced. Japan enjoyed this naval advantage all the way up until Guadalcanal.

        </p>
    </Layout>
)